all:
	kotlinc solve.kt ../../utils/*.kt -d bin

run:
	kotlin -cp bin SolveKt < input

sample:
	kotlin -cp bin SolveKt < sample_input

runF:
	kotlin -cp bin SolveKt -F < input

sampleF:
	kotlin -cp bin SolveKt -F < sample_input
