all:
	kotlinc solve.kt ../../utils/*.kt -d bin

run:
	kotlin -cp bin SolveKt < input

sample:
	kotlin -cp bin SolveKt < sample_input

run2:
	kotlin -cp bin SolveKt p2 < input

sample2:
	kotlin -cp bin SolveKt p2 < sample_input
